# Assignment_17_SVM_(ForestFire)

In [ ]:
classify the Size_Categorie using SVM

month	month of the year: 'jan' to 'dec'
day	day of the week: 'mon' to 'sun'
FFMC	FFMC index from the FWI system: 18.7 to 96.20
DMC	DMC index from the FWI system: 1.1 to 291.3
DC	DC index from the FWI system: 7.9 to 860.6
ISI	ISI index from the FWI system: 0.0 to 56.10
temp	temperature in Celsius degrees: 2.2 to 33.30
RH	relative humidity in %: 15.0 to 100
wind	wind speed in km/h: 0.40 to 9.40
rain	outside rain in mm/m2 : 0.0 to 6.4
Size_Categorie 	the burned area of the forest ( Small , Large)

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

# Acquire the data

In [3]:
df = pd.read_csv('forestfires.csv')

In [7]:
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [6]:
df.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    90.644681  110.872340  547.940039    9.021663   18.889168   44.288201   
std      5.520111   64.046482  248.066192    4.559477    5.806625   16.317469   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   68.600000  437.700000    6.500000   15.500000   33.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  142.400000  713.900000   10.800000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area      dayfri  ...    monthdec  \
count  517.000000  517.000000   517.000000  517.000000  ...  517.000000   
mean     4.017602    0.021663    12.847292    0.164410  ...    0.017408   
std      1.791653    0.295959    63.655818    0.371006  ...    0.130913   
min      0.400000    0.000000     0.000000    0.000000  ...    0.000000   
25%      2.700000    0.000000     0.000000    0.000000  ...    0.000000   
50%      4.000000    0.000000     0.520000    0.000000  ...    0.000000   
75%      4.900000    0.000000     6.570000    0.000000  ...    0.000000   
max      9.400000    6.400000  1090.840000    1.000000  ...    1.000000   

         monthfeb    monthjan    monthjul    monthjun    monthmar    monthmay  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.038685    0.003868    0.061896    0.032882    0.104449    0.003868   
std      0.193029    0.062137    0.241199    0.178500    0.306138    0.062137   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthnov    monthoct    monthsep  
count  517.000000  517.000000  517.000000  
mean     0.001934    0.029014    0.332689  
std      0.043980    0.168007    0.471632  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 28 columns]

# Preprocess the data

In [10]:
df.dtypes
for x in df:
    if df[x].dtypes == "int64":
        df[x] = df[x].astype(float)
        print (df[x].dtypes)

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    float64
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    float64
 10  daymon         517 non-null    float64
 11  daysat         517 non-null    float64
 12  daysun         517 non-null    float64
 13  daythu         517 non-null    float64
 14  daytue         517 non-null    float64
 15  daywed         517 non-null    float64
 16  monthapr       517 non-null    float64
 17  monthaug       517 non-null    float64
 18  monthdec  

In [9]:
df.drop(["month","day"],axis=1,inplace =True)

In [12]:
df.head()

FFMC   DMC     DC  ISI  temp    RH  wind  rain  area  dayfri  ...  \
0  86.2  26.2   94.3  5.1   8.2  51.0   6.7   0.0   0.0     1.0  ...   
1  90.6  35.4  669.1  6.7  18.0  33.0   0.9   0.0   0.0     0.0  ...   
2  90.6  43.7  686.9  6.7  14.6  33.0   1.3   0.0   0.0     0.0  ...   
3  91.7  33.3   77.5  9.0   8.3  97.0   4.0   0.2   0.0     1.0  ...   
4  89.3  51.3  102.2  9.6  11.4  99.0   1.8   0.0   0.0     0.0  ...   

   monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0       0.0       0.0       0.0       0.0       1.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       1.0       0.0       0.0   

   monthoct  monthsep  size_category  
0       0.0       0.0          small  
1       1.0       0.0          small  
2       1.0       0.0          small  
3       0.0       0.0          small  
4       0.0       0.0          small  

[5 rows x 29 columns]

In [14]:
df = df.rename({'size_category': 'size'}, axis=1)
df.head()

FFMC   DMC     DC  ISI  temp    RH  wind  rain  area  dayfri  ...  \
0  86.2  26.2   94.3  5.1   8.2  51.0   6.7   0.0   0.0     1.0  ...   
1  90.6  35.4  669.1  6.7  18.0  33.0   0.9   0.0   0.0     0.0  ...   
2  90.6  43.7  686.9  6.7  14.6  33.0   1.3   0.0   0.0     0.0  ...   
3  91.7  33.3   77.5  9.0   8.3  97.0   4.0   0.2   0.0     1.0  ...   
4  89.3  51.3  102.2  9.6  11.4  99.0   1.8   0.0   0.0     0.0  ...   

   monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0       0.0       0.0       0.0       0.0       1.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       1.0       0.0       0.0   

   monthoct  monthsep   size  
0       0.0       0.0  small  
1       1.0       0.0  small  
2       1.0       0.0  small  
3       0.0       0.0  small  
4       0.0       0.0  small  

[5 rows x 29 columns]

In [16]:
prediction = df.iloc[:,0:28]
target = df.iloc[:,28]

In [18]:
def norm_func(i):
    x= (i-i.min())/(i.max()-i.min())
    return (x)

In [21]:
fires = norm_func(prediction)

In [22]:
fires

FFMC       DMC        DC       ISI      temp        RH      wind  \
0    0.870968  0.086492  0.101325  0.090909  0.192926  0.423529  0.700000   
1    0.927742  0.118194  0.775419  0.119430  0.508039  0.211765  0.055556   
2    0.927742  0.146795  0.796294  0.119430  0.398714  0.211765  0.100000   
3    0.941935  0.110958  0.081623  0.160428  0.196141  0.964706  0.400000   
4    0.910968  0.172984  0.110590  0.171123  0.295820  0.988235  0.155556   
..        ...       ...       ...       ...       ...       ...       ...   
512  0.811613  0.191592  0.771315  0.033868  0.823151  0.200000  0.255556   
513  0.811613  0.191592  0.771315  0.033868  0.633441  0.658824  0.600000   
514  0.811613  0.191592  0.771315  0.033868  0.610932  0.647059  0.700000   
515  0.976774  0.499311  0.711622  0.201426  0.752412  0.317647  0.400000   
516  0.784516  0.006547  0.115867  0.019608  0.308682  0.188235  0.455556   

        rain      area  dayfri  ...  monthdec  monthfeb  monthjan  monthjul  \
0    0.00000  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
1    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
2    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
3    0.03125  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
4    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
..       ...       ...     ...  ...       ...       ...       ...       ...   
512  0.00000  0.005904     0.0  ...       0.0       0.0       0.0       0.0   
513  0.00000  0.049769     0.0  ...       0.0       0.0       0.0       0.0   
514  0.00000  0.010231     0.0  ...       0.0       0.0       0.0       0.0   
515  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
516  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   

     monthjun  monthmar  monthmay  monthnov  monthoct  monthsep  
0         0.0       1.0       0.0       0.0       0.0       0.0  
1         0.0       0.0       0.0       0.0       1.0       0.0  
2         0.0       0.0       0.0       0.0       1.0       0.0  
3         0.0       1.0       0.0       0.0       0.0       0.0  
4         0.0       1.0       0.0       0.0       0.0       0.0  
..        ...       ...       ...       ...       ...       ...  
512       0.0       0.0       0.0       0.0       0.0       0.0  
513       0.0       0.0       0.0       0.0       0.0       0.0  
514       0.0       0.0       0.0       0.0       0.0       0.0  
515       0.0       0.0       0.0       0.0       0.0       0.0  
516       0.0       0.0       0.0       1.0       0.0       0.0  

[517 rows x 28 columns]

In [27]:
from sklearn.preprocessing import LabelEncoder
labelencoder_target = LabelEncoder()
target = labelencoder_target.fit_transform(target)

In [28]:
target

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

In [29]:
from sklearn.svm import SVC

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(prediction,target, test_size = 0.3)

In [35]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 28), (361,), (156, 28), (156,))

In [33]:
X_test

FFMC    DMC     DC   ISI  temp    RH  wind  rain   area  dayfri  ...  \
223  88.3  150.3  309.9   6.8  13.4  79.0   3.6   0.0  37.02     1.0  ...   
213  87.6   52.2  103.8   5.0  11.0  46.0   5.8   0.0  27.35     0.0  ...   
412  92.3   92.1  442.1   9.8  22.8  27.0   4.5   0.0   1.63     0.0  ...   
321  92.8  119.0  783.5   7.5  16.8  28.0   4.0   0.0   7.21     0.0  ...   
161  95.2  131.7  578.8  10.4  20.3  41.0   4.0   0.0   1.90     0.0  ...   
..    ...    ...    ...   ...   ...   ...   ...   ...    ...     ...  ...   
431  92.1  178.0  605.3   9.6  23.3  40.0   4.0   0.0   6.36     0.0  ...   
140  90.9  126.5  686.5   7.0  21.9  39.0   1.8   0.0   0.47     0.0  ...   
156  93.4  145.4  721.4   8.1  28.6  27.0   2.2   0.0   1.61     0.0  ...   
185  91.0  129.5  692.6   7.0  17.6  46.0   3.1   0.0   7.04     0.0  ...   
79   91.0  121.2  561.6   7.0  21.6  19.0   6.7   0.0   0.00     0.0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
223       0.0       0.0       0.0       1.0       0.0       0.0       0.0   
213       0.0       0.0       0.0       0.0       0.0       1.0       0.0   
412       0.0       0.0       0.0       1.0       0.0       0.0       0.0   
321       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
161       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
..        ...       ...       ...       ...       ...       ...       ...   
431       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
140       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
156       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
185       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
79        0.0       0.0       0.0       0.0       0.0       0.0       0.0   

     monthnov  monthoct  monthsep  
223       0.0       0.0       0.0  
213       0.0       0.0       0.0  
412       0.0       0.0       0.0  
321       0.0       0.0       1.0  
161       0.0       0.0       0.0  
..        ...       ...       ...  
431       0.0       0.0       0.0  
140       0.0       0.0       1.0  
156       0.0       0.0       1.0  
185       0.0       0.0       1.0  
79        0.0       0.0       0.0  

[156 rows x 28 columns]

In [36]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1])

In [37]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Train the model

In [51]:
from sklearn.svm import SVC

In [52]:
my_model = SVC(kernel = 'rbf', random_state = 0)
result = my_model.fit(X_train, y_train)

# Test the model

In [39]:
prediction = result.predict(X_test)
prediction

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

## Confusion Matrix

In [5]:
from sklearn.metrics import confusion_matrix
import seaborn as sn

In [6]:
cm = confusion_matrix(y_test, prediction)

NameError: name 'y_test' is not defined

In [46]:
cm

array([[  6,  44],
       [  0, 106]], dtype=int64)

In [7]:
sn.heatmap(cm,annot=True,fmt='2.0f')

NameError: name 'cm' is not defined

## Accuracy

In [48]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, prediction))

Accuracy: 0.717948717948718


## Classification Metrices

In [3]:
from sklearn.metrics import classification_report

In [4]:
# Classification Accuracy
TP = cm[0,0]
TN = cm[1,1]
FP = cm[0,1]
FN = cm[1,0]

NameError: name 'cm' is not defined

In [2]:
classification_accuracy = (TP + TN) / float(TP + TN + FP + FN)
print('Classification accuracy : {0:0.4f}'.format(classification_accuracy))

NameError: name 'TP' is not defined

In [57]:
# Classification error
classification_error = (FP + FN) / float(TP + TN + FP + FN)
print('Classification error : {0:0.4f}'.format(classification_error))

Classification error : 0.2821


## Precision

In [58]:
precision = TP / float(TP + FP)
print('Precision : {0:0.4f}'.format(precision))

Precision : 0.1200


## Recall

In [59]:
recall = TP / float(TP + FN)
print('Recall or Sensitivity : {0:0.4f}'.format(recall))

Recall or Sensitivity : 1.0000


## False Positive Rate

In [60]:
false_positive_rate = FP / float(FP + TN)
print('False Positive Rate : {0:0.4f}'.format(false_positive_rate))

False Positive Rate : 0.2933


In [62]:
from sklearn import metrics
print('\n**Classification Report:\n',metrics.classification_report(y_test, prediction))


**Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.12      0.21        50
           1       0.71      1.00      0.83       106

    accuracy                           0.72       156
   macro avg       0.85      0.56      0.52       156
weighted avg       0.80      0.72      0.63       156



In [74]:
# Kernel = poly
model_poly = SVC(kernel = "poly")
model_poly.fit(X_train,y_train)
pred_test_poly = model_poly.predict(X_test)

In [75]:
np.mean(pred_test_poly==y_test)

0.6794871794871795

In [78]:
#'sigmoid'
model_sig = SVC(kernel = "sigmoid")
model_sig.fit(X_train,y_train)
pred_test_sig = model_sig.predict(X_test)

In [79]:
np.mean(pred_test_sig==y_test)

0.6987179487179487

# Deploy the model

In [64]:
new_pred= list(result.predict([[86.2,26.2,94.3,5.1,8.2,51.0,6.7,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0]]))
new_pred

[1]

In [67]:
new_pred= list(result.predict([[93.9,135.7,586.7,15.1,36.0,5.0,0.0,10.02,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]]))
new_pred

[1]

# Grid Search CV

In [70]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [71]:
gsv.best_params_ , gsv.best_score_ 

({'C': 15, 'gamma': 10, 'kernel': 'rbf'}, 0.7562312312312313)

In [72]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 69.23076923076923


array([[  3,  47],
       [  1, 105]], dtype=int64)